//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminWebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class warning
    {
        public int id { get; set; }
        public string measurement_type { get; set; }
        public Nullable<bool> high { get; set; }
        public Nullable<bool> low { get; set; }
        public string room_name { get; set; }
        public Nullable<System.DateTime> time_stamp { get; set; }
        public Nullable<double> value { get; set; }
    }
}
