//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Sep4_GroupX2Entities : DbContext
    {
        public Sep4_GroupX2Entities()
            : base("name=Sep4_GroupX2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<co2> co2 { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<device> devices { get; set; }
        public virtual DbSet<humidity> humidities { get; set; }
        public virtual DbSet<room> rooms { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<temperature> temperatures { get; set; }
        public virtual DbSet<warning> warnings { get; set; }
    }
}
